<!-- Calendar Grid -->
<div class="p-6">
    <!-- Days of Week Header -->
    <div class="grid grid-cols-7 gap-1 mb-2">
        @foreach(['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'] as $day)
            <div class="text-center py-2 text-sm font-medium text-gray-500 dark:text-gray-400">{{ $day }}</div>
        @endforeach
    </div>

    <!-- Calendar Days -->
    <div id="calendar-grid" class="grid grid-cols-7 gap-1">
        <!-- Calendar days will be generated by JavaScript -->
    </div>
</div>
